const BASE_URL = '<?= base_url() ?>';
const SITE_URL = '<?= site_url() ?>';
const AKTIVER_CONTROLLER = '<?= AKTIVER_CONTROLLER ?>';
const CSRF_NAME = '<?= CSRF_NAME ?>';
const ERSTER_CSRF_HASH = '<?= csrf_hash() ?>';
const ICH_ID = <?= json_encode( ICH_ID, JSON_UNESCAPED_UNICODE ) ?>;
const FORCE_LOCALSTORAGE_RESET_ZEITPUNKT = '<?= FORCE_LOCALSTORAGE_RESET_ZEITPUNKT ?>';

const JANEIN = <?= json_encode( JANEIN, JSON_UNESCAPED_UNICODE ) ?>;
const WOCHENTAGE = <?= json_encode( WOCHENTAGE, JSON_UNESCAPED_UNICODE ) ?>;

const LISTEN = <?= json_encode( LISTEN, JSON_UNESCAPED_UNICODE ) ?>;
const VERKNUEPFUNGEN = <?= json_encode( VERKNUEPFUNGEN, JSON_UNESCAPED_UNICODE ) ?>;
const WERKZEUGE = <?= json_encode( WERKZEUGE, JSON_UNESCAPED_UNICODE ) ?>;
const EIGENSCHAFTEN = <?= json_encode( EIGENSCHAFTEN, JSON_UNESCAPED_UNICODE ) ?>;
const VORGEGEBENE_WERTE = <?= json_encode( VORGEGEBENE_WERTE, JSON_UNESCAPED_UNICODE ) ?>;
const FILTERN_VORGEGEBEN = <?= json_encode( FILTERN_VORGEGEBEN, JSON_UNESCAPED_UNICODE ) ?>;

const FILTERBARE_EIGENSCHAFTEN = <?= json_encode( FILTERBARE_EIGENSCHAFTEN, JSON_UNESCAPED_UNICODE ) ?>;
const SORTIERBARE_EIGENSCHAFTEN = <?= json_encode( SORTIERBARE_EIGENSCHAFTEN, JSON_UNESCAPED_UNICODE ) ?>;
const GRUPPIERBARE_EIGENSCHAFTEN = <?= json_encode( GRUPPIERBARE_EIGENSCHAFTEN, JSON_UNESCAPED_UNICODE ) ?>;

const TERMINE_KATEGORIE_FILTERN_MITGLIEDER = <?= json_encode( TERMINE_KATEGORIE_FILTERN_MITGLIEDER, JSON_UNESCAPED_UNICODE ) ?>;
const TERMINE_KATEGORIE_STATUSSYMBOLE = <?= json_encode( TERMINE_KATEGORIE_STATUSSYMBOLE, JSON_UNESCAPED_UNICODE ) ?>;

const NOTENBANK_ERLAUBTE_DATEITYPEN_NOTEN = <?= json_encode( NOTENBANK_ERLAUBTE_DATEITYPEN_NOTEN, JSON_UNESCAPED_UNICODE ) ?>;
const NOTENBANK_ERLAUBTE_DATEITYPEN_AUDIO = <?= json_encode( NOTENBANK_ERLAUBTE_DATEITYPEN_AUDIO, JSON_UNESCAPED_UNICODE ) ?>;

const SERVERDATA_HOLEN_ZYKLUSZEIT = <?= SERVERDATA_HOLEN_ZYKLUSZEIT ?>;
//const ZUSTAND = Object.freeze({<?php //foreach (ZUSTAND::cases() as $zustand) { echo $zustand->name . ': Symbol("'.$zustand->name.'"), '; } ?>});

const DATENSCHUTZ_RICHTLINIE_DATUM = '<?= DATENSCHUTZ_RICHTLINIE_DATUM ?>';

const SYMBOLE = <?= json_encode( SYMBOLE, JSON_UNESCAPED_UNICODE ) ?>;
const SORT_ASC = <?= SORT_ASC ?>;
const SORT_DESC = <?= SORT_DESC ?>;